#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable init_cell/main
jupyter trust damping_regimes_1.ipynb
jupyter trust damped_driven_1.ipynb
jupyter trust damped_driven_evolultion_1.ipynb
jupyter trust coupled_pendula_2.ipynb
jupyter trust driven_coupled_pendula_1.ipynb
jupyter trust many_coupled_masses_1.ipynb
jupyter trust fourier_series_approx_1.ipynb
jupyter trust progressing_wave_1.ipynb
jupyter trust superposition_1.ipynb
jupyter trust reflection_boundary_1.ipynb
jupyter trust wave_equation_solution_1.ipynb
jupyter trust fourier_decomposition_1.ipynb